name: Publish to Comfy Registry
on:
  push:
    tags: ["v1.0.0"]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Comfy-Org/publish-node-action@v1
        with:
          token: ${{ secrets.COMFYUI }}
